import { NextResponse } from 'next/server';

import { db } from '@/lib/db';

export const runtime = 'nodejs';

export async function GET(req: Request, { params }: { params: { id: string } }) {
  const project = db.getProjectById(params.id);
  if (!project) return NextResponse.json({ error: 'Not found' }, { status: 404 });
  const songs = db.listSongs(project.id);
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${project.name} — Entire Repertoire</title>
  <style>
    body { background: #111; color: #22c55e; font-family: 'LemonMilk', Arial, sans-serif; margin: 0; padding: 2rem; }
    .container { max-width: 600px; margin: 0 auto; background: #181818; border-radius: 12px; box-shadow: 0 2px 12px #0008; padding: 2rem; }
    h1 { font-size: 2rem; margin-bottom: 0.5em; color: #fff; }
    .logo { max-height: 48px; margin-bottom: 1em; }
    table { width: 100%; border-collapse: collapse; margin-top: 1.5em; }
    th, td { padding: 0.5em 0.7em; text-align: left; }
    th { color: #fff; border-bottom: 2px solid #22c55e; }
    td { color: #22c55e; border-bottom: 1px solid #222; }
    .watermark { margin-top: 2em; font-size: 0.9em; color: #666; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    ${project.avatarUrl ? `<img src="${project.avatarUrl}" class="logo" alt="Logo" />` : ''}
    <h1>${project.name} — Entire Repertoire</h1>
    <table>
      <thead><tr><th>Title</th><th>Artist</th></tr></thead>
      <tbody>
        ${songs.map((s) => `<tr><td>${s.title}</td><td>${s.artist}</td></tr>`).join('')}
      </tbody>
    </table>
    <div class="watermark">generated by <span style="color:#22c55e">Song</span><span style="color:#fff">Deck</span></div>
  </div>
</body>
</html>`;
  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' },
  });
}
