import Image from 'next/image';
import { notFound } from 'next/navigation';

import { db } from '@/lib/db';

export const dynamic = 'force-dynamic'; // Always up-to-date

export default async function PublicRepertoirePage({ params }: { params: { id: string } }) {
  const project = db.getProjectById(params.id);
  if (!project) return notFound();
  const songs = db.listSongs(project.id);

  return (
    <div className="min-h-screen bg-black text-green-400 flex items-center justify-center py-8 px-2">
      <div className="w-full max-w-2xl bg-neutral-900 rounded-xl shadow-lg p-8 border border-green-400">
        {project.avatarUrl && (
          <div className="flex justify-center mb-4">
            <Image
              src={project.avatarUrl}
              alt="Logo"
              width={64}
              height={64}
              className="rounded-full"
            />
          </div>
        )}
        <h1 className="text-3xl font-bold text-white mb-2 text-center">
          {project.name} — Entire Repertoire
        </h1>
        <table className="w-full mt-6 border-separate border-spacing-y-2">
          <thead>
            <tr>
              <th className="text-left text-white pb-2">Title</th>
              <th className="text-left text-white pb-2">Artist</th>
            </tr>
          </thead>
          <tbody>
            {songs.map((s) => (
              <tr key={s.id} className="bg-neutral-800">
                <td className="py-2 px-3 text-green-400 font-semibold">{s.title}</td>
                <td className="py-2 px-3 text-green-400">{s.artist}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="mt-8 text-center text-neutral-500 text-sm">
          generated by <span className="text-green-400">Song</span>
          <span className="text-white">Deck</span>
        </div>
      </div>
    </div>
  );
}
